FROM ubuntu:18.04
FROM python:3.10-slim-bookworm

LABEL maintainer="weisiwu <siwu.wsw@gmail.com>"

# 切国内源
RUN cp /etc/apt/sources.list.d/debian.sources /etc/apt/sources.list.d/debian.sources.bak
RUN sed -i 's|http://deb.debian.org/debian|http://mirrors.aliyun.com/debian|g' /etc/apt/sources.list.d/debian.sources

RUN apt update

# 设置工作目录为 /app
WORKDIR /tts_test

# 将当前目录内容复制到位于 /app 的容器中
COPY . /tts_test

RUN pip install --upgrade TTS

# 保持在后台持续运行
CMD ["sleep", "infinity"]
