FROM alpine:3.19
FROM python:3.10-slim-bookworm

LABEL maintainer="weisiwu <siwu.wsw@gmail.com>"

# 尝试运行 MockingBird
# https://github.com/babysor/MockingBird

RUN mkdir -p /etc/apk

RUN echo 'http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.19/main/' > /etc/apk/repositories \
    && echo 'http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.19/community/' >> /etc/apk/repositories

RUN apt-get update && \
    apt-get install -y git && \
    apt-get install -y vim && \
    apt-get install -y wget && \
    apt-get install -y ffmpeg

RUN mkdir -p ~/miniconda3
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
RUN bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
RUN rm -rf ~/miniconda3/miniconda.sh

# 设置工作目录为 /app
WORKDIR /mockingbird_app
RUN git clone https://github.com/babysor/MockingBird.git .

# 安装 requirements.txt 中指定的任何所需包
RUN pip install -r requirements.txt
RUN pip install pyworld
RUN pip install ctc-segmentation
RUN conda env create -n mockingbird_app -f env.yml
RUN conda activate mockingbird_app

# 保持在后台持续运行
# CMD ["python", "ttskit_app.py"]
CMD ["sleep", "infinity"]