FROM alpine:3.19
FROM silverlogic/python3.8:latest

LABEL maintainer="weisiwu <siwu.wsw@gmail.com>"

# 尝试运行 ttskit
# https://github.com/kuangdd/ttskit?tab=readme-ov-file

RUN mkdir -p /etc/apk

RUN echo 'http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.19/main/' > /etc/apk/repositories \
    && echo 'http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.19/community/' >> /etc/apk/repositories

# 设置工作目录为 /app
WORKDIR /ttskit_app

# 将当前目录内容复制到位于 /app 的容器中
COPY ./ttskit_app.py /ttskit_app

# 安装 requirements.txt 中指定的任何所需包
RUN pip install "torch>=1.6.0,<=1.7.1"
RUN pip install -U ttskit

# 保持在后台持续运行
# CMD ["python", "ttskit_app.py"]
CMD ["sleep", "infinity"]