test_arr = [
    "((masterpiece)), best quality, highly detailed, ultra-detailed, official art, Reflecting on the innocence of my youth, with the courage to gaze directly at the sun expressing the jovial fascination I harbored. Fascinated by the minutest of things, inspecting each of their textures, deriving immense joy from the elements beyond their mere physical representations., ((childlike curiosity)), close-up of the sun, awe-stricken eyes, tiny objects, detailed textures, transcendent joy,^^nsfw, worst quality, watermark, disabled, bad anatomy, missing body, deformed eye, extra legs, bad feet, mutated, deformed, malformed, strange, distorted, twins, cropped, blurry, out of frame, disfigured, extra limbs, extra arms, extra legs,",
    "((masterpiece)), best quality, highly detailed, ultra-detailed, official art, The echo of mosquitoes in the summer night replicating thunderous sounds,  orchestrating the ballet of a cranes flock dancers in my mind. Suddenly a multitude of white cranes soared into view, necks stiff from gazing upwards at the spectacular performance., ((Imagination)), summer nights, strident mosquitoes, envisioned cranes, stiff neck, flight formation,^^nsfw, worst quality, watermark, disabled, bad anatomy, missing body, deformed eye, extra legs, bad feet, mutated, deformed, malformed, strange, distorted, twins, cropped, blurry, out of frame, disfigured, extra limbs, extra arms, extra legs,",
    "((masterpiece)), best quality, highly detailed, ultra-detailed, official art, I'd trap a few mosquitoes in a white tent, gently smoke them out. Them flitting towards the smoke, forming the vision of a green cloud mixed with the silhouette of white cranes, mimicking the cranes crying by the edges of the green clouds. A scene deserving of acclaim., ((contrast)), trapped mosquitoes, smoke-caused flight, green veil cloud, silhouette of cranes, applause,^^nsfw, worst quality, watermark, disabled, bad anatomy, missing body, deformed eye, extra legs, bad feet, mutated, deformed, malformed, strange, distorted, twins, cropped, blurry, out of frame, disfigured, extra limbs, extra arms, extra legs,",
    "((masterpiece)), best quality, highly detailed, ultra-detailed, official art, In the uneven terrain of the mud wall and the overgrown flower stand, I'd squat as a spectator of nature's play. My imagination transformed the clump of grass into a dense forest, bugs and ants became wildlife, outgrowths of earth impersonated hills and the indents valleys, thus my imaginary escapade in this miniature world brought me joy and contentment., ((transformative creativity)), uneven mud walls, overgrown flower stand, miniature depiction, forest, wildlife, hills, valleys, escapade, joy, contentment,^^nsfw, worst quality, watermark, disabled, bad anatomy, missing body, deformed eye, extra legs, bad feet, mutated, deformed, malformed, strange, distorted, twins, cropped, blurry, out of frame, disfigured, extra limbs, extra arms, extra legs,",
    "((masterpiece)), best quality, highly detailed, ultra-detailed, official art, Once, intrigued by two insects battling in the grass, a monstrous creature appeared, disturbing the silent fight: a toad. With a swift move of its tongue, it devoured both combatants, leaving me shocked., ((dramatic action)), two insects, battle scene, monstrous toad, shock,^^nsfw, worst quality, watermark, disabled, bad anatomy, missing body, deformed eye, extra legs, bad feet, mutated, deformed, malformed, strange, distorted, twins, cropped, blurry, out of frame, disfigured, extra limbs, extra arms, extra legs,",
    "((masterpiece)), best quality, highly detailed, ultra-detailed, official art, At that young age, unaccustomed to the cruel realities of nature, I let out a frightful shout, caught in the raw emotion of the moment., ((childish innocence)), young age, fright, surprise,^^nsfw, worst quality, watermark, disabled, bad anatomy, missing body, deformed eye, extra legs, bad feet, mutated, deformed, malformed, strange, distorted, twins, cropped, blurry, out of frame, disfigured, extra limbs, extra arms, extra legs,",
    "((masterpiece)), best quality, highly detailed, ultra-detailed, official art, Once my senses returned, I held onto the toad and punished it for its merciless nature, chasing it away to a different court. This was my naive form of justice., ((justifiable actions)), toad, punishment, enactment of justice,^^nsfw, worst quality, watermark, disabled, bad anatomy, missing body, deformed eye, extra legs, bad feet, mutated, deformed, malformed, strange, distorted, twins, cropped, blurry, out of frame, disfigured, extra limbs, extra arms, extra legs,",
]

for item in test_arr:
    a, b = item.strip().split("^^")
    print("item__", a, "+++++++++", b)
